### ISSUE TITLE
Wrong return of Voice_processor.py extract_features

### ISSUE THREAD

**Issue by zwvews** [pdkit/pdkit#107] opened 2019-11-26 00:01 UTC
## Expected Behavior
The extract_features function returns f0_max, f_0quan25, and f0_quan75 with same value which is clearly wrong

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by pdkit** [comment] 2019-11-27 16:53
Thank you very much for raising this issue, we very much appreciate your support. However, we are not able to replicate the issue with the little information you provided. The problem reported does not occur in any of the files we use for testing so providing the additional information to help us reproduce the problem is critical.

It would be most helpful if you could provide a more detailed description but for the time being we will have to close this issue due to lack of adequate information to replicate the problem.

**Closed by pdkit** 2019-11-27 16:53 UTC
